#!/usr/bin/env python3
from pathlib import Path
import re
p = Path('app/index.html')
html = p.read_text(encoding='utf-8')
SCRIPTS = [
    ('employee-nickname.js', '4'),
    ('sales-commission-edit.js', '1'),
    ('sales-achievements-edit.js', '1'),
    ('dashboard-ai-layout.js', '4'),
    ('pv-bank-account.js', '1'),
    ('print-hide-fabs.js', '1'),
    ('role-permissions-sync.js', '9'),
    ('booking.js', '1'),
    ('booking-shortcut.js', '1'),
    ('booking-token-fix.js', '1'),
    ('booking-public-contrast.js', '1'),
    ('pdoc-invoice-terms.js', '4'),
    ('pv-desc-wrap.js', '1'),
    ('pv-preview-scroll.js', '3'),
    ('pdoc-preview-light.js', '1'),
    ('booking-state.js', '2'),
    ('booking-settings-ui.js', '1'),
    ('booking-realtime.js', '1'),
    ('booking-card-ui.js', '2'),
    ('crm-scan.js', '1'),
    ('employee-probation.js', '2'),
    ('employee-probation-save.js', '3'),
    ('employee-form-id.js', '2'),
    ('employment-status-select.js', '1'),
    ('employee-join-date.js', '1'),
    ('att-tracker-today.js', '1'),
    ('probation-dash.js', '3'),
    ('hr-list-nickname.js', '1'),
    ('probation-dialog-contrast.js', '2'),
    ('leave-half-day.js', '1'),
    ('leave-row-detail.js', '3'),
    ('leave-slip.js', '4'),
    ('leave-email-click.js', '1'),
    ('outstation-amend.js', '1'),
    ('doc-drive-root.js', '2'),
    ('doc-oauth-lock.js', '2'),
    ('docs-token-hook.js', '1'),
    ('docs-drive-persist.js', '4'),
    ('docs-drive-label.js', '1'),
    ('docs-seed.js', '7'),
    ('docs-content-scan.js', '4'),
    ('docs-classify.js', '7'),
    ('docs-slot-fix.js', '4'),
    ('docs-ai-apply.js', '1'),
    ('docs-filename.js', '4'),
    ('docs-upload-fix.js', '1'),
    ('doc-wrap.js', '1'),
    ('doc-router-admin.js', '6'),
    ('expense-claims-access.js', '1'),
    ('expense-claim-staff-apply.js', '2'),
    ('admin-clients-plans.js', '2'),
    ('admin-clients-dates.js', '2'),
    ('staff-hr-access.js', '1'),
    ('acc-full-tabs.js', '1'),
    ('dash-insight-nickname.js', '1'),
    ('support-tenant.js', '2'),
    ('plan-code-fix.js', '1'),
    ('admin-content-mobile.js', '2'),
    ('admin-team-table.js', '1'),
    ('admin-audit-filter.js', '1'),
    ('dash-topsp-sales.js', '3'),
    ('dash-ai-paint.js', '1'),
    ('crm-table-fit.js', '2'),
    ('inv-table-fit.js', '1'),
    ('sl-items-fit.js', '1'),
    ('prod-table-fit.js', '1'),
    ('do-table-fit.js', '1'),
    ('list-table-fit.js', '3'),
    ('reco-print.js', '4'),
    ('reco-sort-filter.js', '2'),
    ('jnl-print.js', '2'),
    ('jnl-search.js', '1'),
    ('coa-seed-advanced.js', '2'),
    ('sd-employer-edit.js', '6'),
]
for name, ver in SCRIPTS:
    tag = '<script src="./'+name+'?v='+ver+'"></script>'
    if name not in html:
        html = html.replace('</body>', tag+'\n</body>', 1)
    else:
        html = re.sub(re.escape(name)+r'\?v=\d+', name+'?v='+ver, html)
p.write_text(html, encoding='utf-8')
print('ok')
