-- Learning Center content seed: 14 chapters, one lesson (or a small
-- lesson set for the bigger modules: Sales, HR, Accounting), and
-- numbered steps per lesson.
--
-- Content is grounded in the actual current app/index.html render
-- functions (renderCRM, renderSales, renderPOS, renderInventory,
-- renderPurchasing, renderProduction, renderLogistics, renderHR,
-- renderJobApplicants, renderAccounting, renderPaymentVouchers,
-- renderReports) as of this migration's date — real button/tab
-- labels, real business-logic nuances (e.g. Sales KPIs count
-- Paid+Partial invoices as recognised revenue, not just Paid; Reorder
-- Point defaults to 5 when unset; a Purchase Order can be partially
-- received; Production/Logistics are deliberately simple MVPs with
-- manual status and no automatic stock/GPS behaviour; HR payroll
-- statutory calculations are estimates that must be verified before
-- official submission).
--
-- Column names assumed (not independently verified against the live
-- schema since this session has no direct Supabase access):
--   learning_chapters(id uuid pk, module_key text, sort_order int,
--     title_en text, title_bm text, intro_en text, intro_bm text)
--   learning_lessons(id uuid pk, chapter_id uuid fk, sort_order int,
--     title_en text, title_bm text, intro_en text, intro_bm text)
--   learning_steps(id uuid pk, lesson_id uuid fk, step_no int,
--     text_en text, text_bm text, field_note_en text, field_note_bm text,
--     try_it_page text)
-- If any of these differ from the live table, tell me the real column
-- names and I will patch this script quickly (same recovery pattern as
-- the earlier referral_conversions schema mismatch this session).

-- ─── Chapters ────────────────────────────────────────────────────────────
INSERT INTO learning_chapters (id, module_key, sort_order, title_en, title_bm, intro_en, intro_bm) VALUES
('25c4bfab-573f-451f-b8a6-47a0b39bb23e', 'register', 1, 'Register & Onboarding', 'Daftar & Onboarding',
 'This is where your business first meets M-Core: creating your tenant, choosing a plan, and getting your team in. Understanding the trial-vs-paid distinction now saves confusion later when a feature suddenly needs an upgrade.',
 'Di sinilah bisnes anda mula-mula berkenalan dengan M-Core: cipta tenant, pilih pelan, dan bawa masuk pasukan anda. Faham beza trial lawan pelan berbayar dari awal elak kekeliruan bila satu ciri tiba-tiba perlukan naik taraf.'),
('d583b61b-c172-4b6f-a454-fc93380a7c64', 'dashboard', 2, 'Dashboard', 'Papan Pemuka',
 'The Dashboard is the first thing you should check every morning — it compresses your whole business into a handful of numbers and charts so you know where to look before you go digging through every module.',
 'Papan Pemuka adalah perkara pertama yang patut anda semak setiap pagi — ia mampatkan seluruh bisnes anda jadi beberapa nombor dan carta supaya anda tahu di mana nak tumpu sebelum menggali setiap modul satu-satu.'),
('5798ffa6-768c-4210-af29-d0cb579e101e', 'crm', 3, 'CRM', 'CRM',
 'CRM here means your Customers — the people and companies you sell to. It is the single list every quotation, invoice and POS sale pulls from, so keeping it clean matters more than it looks.',
 'CRM di sini bermaksud Pelanggan anda — orang dan syarikat yang anda jual kepada. Ia senarai tunggal yang setiap sebut harga, invois dan jualan POS rujuk, jadi jaga kekemasannya lebih penting dari yang disangka.'),
('ac4547af-2fb3-4fb6-a739-c200b0c0e1c3', 'sales', 4, 'Sales', 'Jualan',
 'Sales covers the whole money-in journey: quoting a price, turning it into a real invoice, getting paid (fully or partially), chasing what is overdue, and correcting mistakes with a Credit Note. Each stage means something different legally and in your reports — this chapter walks through all five.',
 'Jualan meliputi seluruh perjalanan duit-masuk: beri sebut harga, tukar jadi invois sebenar, terima bayaran (penuh atau sebahagian), kejar yang tertunggak, dan betulkan kesilapan dengan Nota Kredit. Setiap peringkat bermaksud lain dari segi undang-undang dan laporan — bab ini lalui kelima-lima.'),
('35385c99-8814-4491-ac93-02e62ade9c66', 'pos', 5, 'POS', 'POS',
 'Point of Sale is for counter/walk-in sales — fast, cash-register style, with stock deducted the moment a sale completes. It runs on its own shift system so cash handling stays accountable per staff member per shift.',
 'Point of Sale untuk jualan kaunter/walk-in — pantas, gaya mesin daftar tunai, dengan stok ditolak sebaik sahaja jualan selesai. Ia berjalan atas sistem shift sendiri supaya pengendalian tunai kekal bertanggungjawab bagi setiap staf setiap shift.'),
('97d8d4d9-a769-4b85-be09-5eb76c40f323', 'inventory', 6, 'Inventory', 'Inventori',
 'Inventory is where your products live and where every stock change gets logged — sales, purchases, adjustments. Understanding Reorder Point and Stock Movements means you catch a stock-out before your customer does.',
 'Inventori adalah tempat produk anda dan tempat setiap perubahan stok direkod — jualan, belian, pelarasan. Faham Takat Pesan Semula dan Pergerakan Stok bermakna anda dapat kesan kehabisan stok sebelum pelanggan anda perasan.'),
('987648d6-0d17-47c7-bc48-958977f8c45e', 'purchasing', 7, 'Purchasing', 'Perolehan',
 'Purchasing is a 3-stage flow — Purchase Order (a plan), Goods Received Note (what actually arrived, which can be partial), and Supplier Bill (what you owe and pay). Skipping straight to a Bill without a PO/GRN loses the paper trail that protects you when a supplier under-delivers.',
 'Perolehan adalah aliran 3-peringkat — Pesanan Belian (rancangan), Nota Terima Barang/GRN (apa yang betul-betul sampai, boleh separa), dan Bil Pembekal (apa yang anda tanggung dan bayar). Terus ke Bil tanpa PO/GRN hilang jejak rekod yang melindungi anda bila pembekal hantar kurang.'),
('807c368e-7d8e-4eac-92e4-39e005db9096', 'production', 8, 'Production', 'Pengeluaran',
 'Production tracks a Work Order — what you are making, how much, and its status — as a deliberately simple MVP. It does not (yet) auto-deduct raw materials from Inventory, so know what it does and does not do before you rely on it.',
 'Pengeluaran menjejak Work Order — apa yang dibuat, berapa banyak, dan statusnya — sebagai MVP yang sengaja ringkas. Ia tidak (buat masa ini) menolak bahan mentah dari Inventori secara automatik, jadi faham apa yang ia buat dan tak buat sebelum bergantung padanya.'),
('cd9a7a6a-a86b-41ad-9761-30e8209a66e5', 'logistics', 9, 'Logistics', 'Logistik',
 'Logistics tracks delivery status for outgoing orders — also a simple MVP with manual status updates, not live GPS. It is only as accurate as whoever last updated it.',
 'Logistik menjejak status penghantaran untuk pesanan keluar — juga MVP ringkas dengan kemas kini status manual, bukan GPS langsung. Ia hanya setepat orang terakhir yang mengemas kininya.'),
('4c275440-9ef4-4774-98a2-61e3cd4d05a4', 'hr', 10, 'HR & Payroll', 'SDM & Gaji',
 'HR & Payroll covers your people end-to-end: employee records, attendance, leave/outstation, and running payroll through to Salary Disbursement and the Payslip. The statutory calculations (EPF/SOCSO/EIS/PCB) are estimates you should verify — this chapter tells you exactly why.',
 'SDM & Gaji meliputi orang anda dari hujung ke hujung: rekod pekerja, kehadiran, cuti/outstation, dan jalankan gaji sehingga Penyaluran Gaji dan Payslip. Kalkulasi berkanun (EPF/SOCSO/EIS/PCB) adalah anggaran yang perlu disahkan — bab ini terangkan kenapa dengan tepat.'),
('0af18bc3-71dd-4e3a-8166-6df257173109', 'applicants', 11, 'Job Applicants', 'Permohonan Kerja',
 'Job Applicants is your recruitment pipeline, separate from Employees until you actually hire someone — then one click converts an applicant into a real employee record without retyping anything.',
 'Permohonan Kerja adalah saluran pengambilan pekerja anda, berasingan dari Pekerja sehingga anda betul-betul mengambil seseorang — kemudian satu klik tukar pemohon jadi rekod pekerja sebenar tanpa taip semula apa-apa.'),
('eddbc17b-8539-4770-8853-cc8589e9f9d5', 'accounting', 12, 'Accounting', 'Perakaunan',
 'Accounting is the backbone every other module quietly feeds into — most transactions (paid invoices, POS sales, approved claims, paid bills, payroll, paid vouchers) already auto-post their own journal entries. This chapter covers the six areas you will actually touch by hand: Chart of Accounts, Journal Entries, Fiscal Year & Period Lock, Expense Claims, Petty Cash, and Bank Reconciliation.',
 'Perakaunan adalah tulang belakang yang disokong senyap oleh setiap modul lain — kebanyakan transaksi (invois dibayar, jualan POS, tuntutan diluluskan, bil dibayar, gaji, baucar dibayar) dah auto-siar entri jurnal sendiri. Bab ini meliputi 6 bahagian yang anda betul-betul akan sentuh sendiri: Carta Akaun, Entri Jurnal, Tahun Kewangan & Kunci Tempoh, Tuntutan Perbelanjaan, Petty Cash, dan Penyesuaian Bank.'),
('8f6ca22d-7f60-4ac3-a934-39bf36801be2', 'vouchers', 13, 'Payment Vouchers', 'Baucar Bayaran',
 'Payment Vouchers are the formal paper trail for money leaving the business outside the usual supplier-bill flow — rent, utilities, ad-hoc payments — and they post straight to the ledger.',
 'Baucar Bayaran adalah rekod rasmi untuk duit keluar dari bisnes di luar aliran bil-pembekal biasa — sewa, utiliti, bayaran ad-hoc — dan ia terus disiar ke lejar.'),
('1a3fa894-cf1c-4e7f-83b4-2d5c58dd6d30', 'reports', 14, 'Reports', 'Laporan',
 'Reports turn everything you have recorded into the three documents that actually answer "how is my business doing": the Income Statement (profit), the Balance Sheet (what you own vs owe), and the Sales Report (who and what is driving revenue).',
 'Laporan menukar semua yang direkod jadi tiga dokumen yang betul-betul jawab "macam mana bisnes saya" — Penyata Pendapatan (untung), Kunci Kira-kira (apa dimiliki lawan ditanggung), dan Laporan Jualan (siapa dan apa yang menjana hasil).');

-- ─── Lessons ─────────────────────────────────────────────────────────────
INSERT INTO learning_lessons (id, chapter_id, sort_order, title_en, title_bm, intro_en, intro_bm) VALUES
('4bd85981-867a-4fe8-a296-5131d887f038', '25c4bfab-573f-451f-b8a6-47a0b39bb23e', 1,
 'Trial vs Paid Plans, and Inviting Your Team', 'Pelan Percubaan lawan Berbayar, dan Jemput Pasukan Anda',
 'Every tenant starts on a trial so you can test M-Core before spending a ringgit. Knowing what the trial actually unlocks — and what happens when it ends — avoids a nasty surprise mid-month.',
 'Setiap tenant mula dengan percubaan supaya anda boleh uji M-Core sebelum belanja seringgit pun. Tahu apa yang percubaan betul-betul buka — dan apa jadi bila ia tamat — elak kejutan tak elok tengah bulan.'),

('fe61436e-7902-45c7-b50e-6fecb9d42043', 'd583b61b-c172-4b6f-a454-fc93380a7c64', 1,
 'Reading Your Dashboard', 'Membaca Papan Pemuka Anda',
 'Every chart on the Dashboard is answering a specific question about your business. This lesson goes card by card so you know exactly what each number is telling you, not just what it looks like.',
 'Setiap carta pada Papan Pemuka menjawab soalan khusus tentang bisnes anda. Pelajaran ini pergi kad demi kad supaya anda tahu tepat apa setiap nombor beritahu, bukan sekadar rupanya.'),

('adb1d67f-0da9-422e-95bf-8be61acd03d6', '5798ffa6-768c-4210-af29-d0cb579e101e', 1,
 'Adding & Managing Customers', 'Tambah & Urus Pelanggan',
 'A customer record you add once gets reused everywhere — quotations, invoices, POS. Get it right the first time and every downstream document just works.',
 'Rekod pelanggan yang anda tambah sekali digunakan semula di mana-mana — sebut harga, invois, POS. Betulkan dari awal dan setiap dokumen selepasnya terus berfungsi.'),

('4a61893a-3454-4d82-96f7-50b41a09617b', 'ac4547af-2fb3-4fb6-a739-c200b0c0e1c3', 1,
 'Create a Quotation', 'Cipta Sebut Harga',
 'A Quotation is a price offer, not a bill — it does not touch your revenue reports or receivables until someone actually converts it. Use it whenever a customer needs to see a price before committing.',
 'Sebut Harga adalah tawaran harga, bukan bil — ia tak sentuh laporan hasil atau piutang anda sehingga seseorang betul-betul menukarnya. Guna bila-bila pelanggan perlu lihat harga sebelum komited.'),

('cc8d3411-f3b9-43af-b84f-544e13d52790', 'ac4547af-2fb3-4fb6-a739-c200b0c0e1c3', 2,
 'Convert Quotation to Invoice', 'Tukar Sebut Harga kepada Invois',
 'The moment a Quotation becomes an Invoice is the moment it becomes a real, collectible amount owed to you. This lesson covers exactly when and how to make that switch.',
 'Saat Sebut Harga bertukar jadi Invois adalah saat ia jadi jumlah sebenar yang boleh dikutip dan tertanggung kepada anda. Pelajaran ini meliputi tepat bila dan macam mana buat pertukaran itu.'),

('acfb18e1-a700-4f5e-9c7e-914695657b5e', 'ac4547af-2fb3-4fb6-a739-c200b0c0e1c3', 3,
 'Record a Payment (Full or Partial)', 'Rekod Bayaran (Penuh atau Sebahagian)',
 'How you record a payment decides whether that invoice counts as collected revenue on your Dashboard. This lesson covers full payments, partial payments, and why "Partial" is treated almost the same as "Paid" everywhere else in the system.',
 'Cara anda rekod bayaran menentukan sama ada invois itu dikira sebagai hasil dikutip pada Papan Pemuka anda. Pelajaran ini meliputi bayaran penuh, bayaran sebahagian, dan kenapa "Partial" dianggap hampir sama dengan "Paid" di tempat lain dalam sistem.'),

('2c5cbb0a-e25d-47fa-acba-be79cd4272d9', 'ac4547af-2fb3-4fb6-a739-c200b0c0e1c3', 4,
 'Manage Overdue Invoices', 'Uruskan Invois Tertunggak',
 'An invoice becomes Overdue on its own — you do not mark it. Knowing exactly what makes an invoice "Overdue" (and what stops counting once it does not) helps you chase the right customers at the right time.',
 'Invois jadi Tertunggak dengan sendirinya — anda tak tandakannya. Tahu tepat apa yang buat invois "Tertunggak" (dan apa yang berhenti dikira sebaik ia bertukar) bantu anda kejar pelanggan yang betul pada masa yang betul.'),

('6bb9b7ac-584b-4352-b697-bd014547e871', 'ac4547af-2fb3-4fb6-a739-c200b0c0e1c3', 5,
 'Credit Notes & Refunds', 'Nota Kredit & Bayaran Balik',
 'Mistakes and returns happen — a Credit Note corrects an invoice without deleting it, keeping your paper trail intact for audit and for the customer.',
 'Kesilapan dan pemulangan berlaku — Nota Kredit betulkan invois tanpa memadamnya, mengekalkan jejak rekod untuk audit dan untuk pelanggan.'),

('7f887d1b-6d63-4b5f-80bf-9b2ade7bce93', '35385c99-8814-4491-ac93-02e62ade9c66', 1,
 'Running a POS Shift & Sale', 'Menjalankan Shift & Jualan POS',
 'POS is built around shifts, not just sales — every cashier opens a shift with a cash float and closes it with a cash count, so any discrepancy is caught at the shift level, not buried in a whole day of transactions.',
 'POS dibina sekitar shift, bukan sekadar jualan — setiap kasir buka shift dengan float tunai dan tutup dengan kiraan tunai, supaya sebarang percanggahan dikesan di peringkat shift, bukan tertimbus dalam sehari penuh transaksi.'),

('f722fd53-cc85-476b-b30c-d3d1089b0ca1', '97d8d4d9-a769-4b85-be09-5eb76c40f323', 1,
 'Products, Stock Movements & Reorder Points', 'Produk, Pergerakan Stok & Takat Pesan Semula',
 'Every unit of stock that moves in or out of your business — sold, received, adjusted — gets logged as a Stock Movement, and Reorder Point is what turns that raw log into an early warning.',
 'Setiap unit stok yang keluar-masuk bisnes anda — dijual, diterima, dilaraskan — direkod sebagai Pergerakan Stok, dan Takat Pesan Semula adalah apa yang tukar rekod mentah itu jadi amaran awal.'),

('6d5cd36a-3724-4d96-befe-159f045f523d', '987648d6-0d17-47c7-bc48-958977f8c45e', 1,
 'Purchase Order → GRN → Supplier Bill', 'Pesanan Belian → GRN → Bil Pembekal',
 'Buying stock is a 3-step story, not one screen: you plan it (PO), you confirm what actually arrived (GRN — which can be less than ordered), then you settle what you owe (Bill). Skip a step and you lose the ability to prove what really happened.',
 'Beli stok adalah cerita 3-langkah, bukan satu skrin: anda rancang (PO), sahkan apa yang betul-betul sampai (GRN — boleh kurang dari dipesan), kemudian selesaikan apa yang ditanggung (Bil). Lompat satu langkah, anda hilang keupayaan buktikan apa yang sebenarnya berlaku.'),

('6da56a89-9e04-45e2-9b39-69327bc9e81b', '807c368e-7d8e-4eac-92e4-39e005db9096', 1,
 'Creating & Tracking a Work Order', 'Cipta & Jejak Work Order',
 'A Work Order tells your team what to make and how much — but this module is a deliberately simple MVP, so know its one big limitation before you plan around it.',
 'Work Order beritahu pasukan anda apa nak buat dan berapa banyak — tapi modul ini sengaja MVP ringkas, jadi tahu satu had besarnya sebelum merancang berdasarkannya.'),

('2d7e263e-cf00-480a-9f6e-d050165367e5', 'cd9a7a6a-a86b-41ad-9761-30e8209a66e5', 1,
 'Tracking Delivery Status', 'Menjejak Status Penghantaran',
 'A Delivery Order links an outgoing shipment to a driver and vehicle, and its status is updated by hand — this lesson tells you what that means for how reliable that status actually is.',
 'Delivery Order kaitkan penghantaran keluar dengan pemandu dan kenderaan, dan statusnya dikemas kini secara manual — pelajaran ini beritahu apa maksudnya untuk seberapa boleh dipercayai status itu sebenarnya.'),

('dc922c5b-5915-4006-90a4-03117e50101d', '4c275440-9ef4-4774-98a2-61e3cd4d05a4', 1,
 'Employees & Attendance', 'Pekerja & Kehadiran',
 'The Employee record is the source every payroll calculation reads from, and Attendance is how you know who actually showed up to earn it.',
 'Rekod Pekerja adalah sumber yang dibaca setiap kiraan gaji, dan Kehadiran adalah cara anda tahu siapa yang betul-betul hadir untuk menerimanya.'),

('95dc6ad7-6626-4084-b3bd-1af76063d039', '4c275440-9ef4-4774-98a2-61e3cd4d05a4', 2,
 'Leave & Outstation', 'Cuti & Outstation',
 'Leave and Outstation both need approval before they are official — this lesson covers the request-and-approve flow for both.',
 'Cuti dan Outstation kedua-duanya perlu kelulusan sebelum ia rasmi — pelajaran ini meliputi aliran mohon-dan-lulus untuk kedua-duanya.'),

('3a3402f4-9515-49dc-8dde-a80a53518fcf', '4c275440-9ef4-4774-98a2-61e3cd4d05a4', 3,
 'Running Payroll & Salary Disbursement', 'Menjalankan Gaji & Penyaluran Gaji',
 'Run Payroll calculates EPF/SOCSO/EIS/PCB for every employee at once — but the system is upfront that these are estimates, not the exact official tables. This lesson explains exactly why that distinction matters before you submit anything officially.',
 'Jalankan Gaji kira EPF/SOCSO/EIS/PCB untuk setiap pekerja serentak — tapi sistem terus terang ini adalah anggaran, bukan jadual rasmi tepat. Pelajaran ini terangkan tepat kenapa beza itu penting sebelum anda serahkan apa-apa secara rasmi.'),

('f1eb4e45-20d3-4482-99fc-38dc6629a28a', '4c275440-9ef4-4774-98a2-61e3cd4d05a4', 4,
 'Understanding the Payslip', 'Memahami Payslip',
 'A Payslip is not just a PDF — every line on it maps to a real calculation. This lesson breaks down what each section actually means.',
 'Payslip bukan sekadar PDF — setiap baris di dalamnya memetakan kepada kiraan sebenar. Pelajaran ini pecahkan apa maksud sebenar setiap bahagian.'),

('0dbe7d33-e07d-4f3b-850e-92f7b9675efa', '0af18bc3-71dd-4e3a-8166-6df257173109', 1,
 'Managing Applicants & Hiring', 'Uruskan Pemohon & Pengambilan',
 'Applicants stay separate from your Employee list until you actually hire someone — then one click carries their details over so you never retype a hire''s information twice.',
 'Pemohon kekal berasingan dari senarai Pekerja anda sehingga anda betul-betul mengambil seseorang — kemudian satu klik bawa maklumat mereka supaya anda tak pernah taip semula maklumat pekerja baru dua kali.'),

('2c2f22e1-57cb-4d64-921c-fd5d242f59cd', 'eddbc17b-8539-4770-8853-cc8589e9f9d5', 1,
 'Chart of Accounts', 'Carta Akaun',
 'The Chart of Accounts is the master list every single financial number in the system eventually lands in — it was seeded for you at onboarding, but you own it from here.',
 'Carta Akaun adalah senarai induk yang setiap nombor kewangan dalam sistem akhirnya mendarat — ia dah disemai untuk anda semasa onboarding, tapi ia milik anda dari sini.'),

('fb8c85c0-a7af-4e63-ab0d-8ef27bda6b82', 'eddbc17b-8539-4770-8853-cc8589e9f9d5', 2,
 'Journal Entries', 'Entri Jurnal',
 'Most of your journal entries write themselves — this lesson explains what auto-posts on its own, and the much smaller set of situations where you actually need to post one by hand.',
 'Kebanyakan entri jurnal anda tulis sendiri — pelajaran ini terangkan apa yang auto-siar dengan sendirinya, dan situasi yang jauh lebih kecil di mana anda betul-betul perlu siar sendiri.'),

('affa6c55-95ca-49db-865d-8f9d3c5ca7b6', 'eddbc17b-8539-4770-8853-cc8589e9f9d5', 3,
 'Fiscal Year & Period Lock', 'Tahun Kewangan & Kunci Tempoh',
 'Fiscal Year defines when your financial year starts; Period Lock is the safety switch that stops anyone — including you — from accidentally editing a month you have already closed off.',
 'Tahun Kewangan tentukan bila tahun kewangan anda bermula; Kunci Tempoh adalah suis keselamatan yang halang sesiapa — termasuk anda — daripada tersalah edit bulan yang dah anda tutup.'),

('0c660df7-7548-48e6-af06-a432a2a2d43f', 'eddbc17b-8539-4770-8853-cc8589e9f9d5', 4,
 'Expense Claims', 'Tuntutan Perbelanjaan',
 'Expense Claims let staff get reimbursed for money they spent on the business — with an approval step so nothing posts to the books unchecked.',
 'Tuntutan Perbelanjaan bagi staf terima balik duit yang mereka belanja untuk bisnes — dengan langkah kelulusan supaya tiada apa disiar ke buku tanpa disemak.'),

('3a3edc5f-c25b-4ac2-bcd3-9755e7a0f6c3', 'eddbc17b-8539-4770-8853-cc8589e9f9d5', 5,
 'Petty Cash', 'Petty Cash',
 'Petty Cash is a small physical cash fund for tiny day-to-day expenses that do not deserve a full Payment Voucher — this lesson covers how to keep it reconciled.',
 'Petty Cash adalah dana tunai fizikal kecil untuk perbelanjaan harian kecil yang tak layak Baucar Bayaran penuh — pelajaran ini meliputi cara kekalkannya seimbang.'),

('a52f4c27-2e42-4e5c-924c-5d32b201aebd', 'eddbc17b-8539-4770-8853-cc8589e9f9d5', 6,
 'Bank Reconciliation', 'Penyesuaian Bank',
 'Bank Reconciliation compares what your bank statement says against what you have recorded, with the system suggesting matches for you — but a suggestion is not a confirmation, and this lesson explains why you should always double-check.',
 'Penyesuaian Bank bandingkan apa penyata bank kata lawan apa yang anda dah rekod, dengan sistem cadangkan padanan untuk anda — tapi cadangan bukan pengesahan, dan pelajaran ini terangkan kenapa anda patut sentiasa semak semula.'),

('0ce7df18-11da-429c-99e6-846bd4321704', '8f6ca22d-7f60-4ac3-a934-39bf36801be2', 1,
 'Creating & Printing Payment Vouchers', 'Cipta & Cetak Baucar Bayaran',
 'A Payment Voucher is your formal record for a payment that does not go through the usual Supplier Bill flow — think rent, utilities, or a one-off payment — and it posts straight to your ledger.',
 'Baucar Bayaran adalah rekod rasmi anda untuk bayaran yang tak lalui aliran Bil Pembekal biasa — fikir sewa, utiliti, atau bayaran sekali sahaja — dan ia terus disiar ke lejar anda.'),

('9639df7e-aaa6-4fd5-90a4-5784e684329f', '1a3fa894-cf1c-4e7f-83b4-2d5c58dd6d30', 1,
 'Income Statement, Balance Sheet & Sales Report', 'Penyata Pendapatan, Kunci Kira-kira & Laporan Jualan',
 'Three reports, three different questions: is the business profitable, what does it actually own versus owe, and who/what is actually driving the numbers. This lesson teaches you to read all three, not just glance at the totals.',
 'Tiga laporan, tiga soalan berbeza: adakah bisnes untung, apa yang betul-betul dimiliki lawan ditanggung, dan siapa/apa yang betul-betul menjana nombor. Pelajaran ini ajar anda baca ketiga-tiganya, bukan sekadar pandang jumlah besar.');

-- ─── Steps ───────────────────────────────────────────────────────────────
INSERT INTO learning_steps (id, lesson_id, step_no, text_en, text_bm, field_note_en, field_note_bm, try_it_page) VALUES

-- register
(gen_random_uuid(), '4bd85981-867a-4fe8-a296-5131d887f038', 1,
 'When you register, your tenant starts on a free trial so you can explore the whole system before paying anything.',
 'Bila anda daftar, tenant anda mula dengan percubaan percuma supaya anda boleh terokai seluruh sistem sebelum bayar apa-apa.',
 'A trial is time-limited. Once it ends without an upgrade, some features may lock until you choose a paid plan — this protects you from being charged before you have decided M-Core fits your business.',
 'Percubaan ada had masa. Bila ia tamat tanpa naik taraf, sesetengah ciri mungkin dikunci sehingga anda pilih pelan berbayar — ini lindungi anda daripada dikenakan bayaran sebelum anda putuskan M-Core sesuai untuk bisnes anda.',
 NULL),
(gen_random_uuid(), '4bd85981-867a-4fe8-a296-5131d887f038', 2,
 'During onboarding you pick your industry and a starter Chart of Accounts template, seeding Accounting with accounts that already match how a Malaysian SME actually operates.',
 'Semasa onboarding anda pilih industri dan templat Carta Akaun permulaan, menyemai Perakaunan dengan akaun yang dah padan macam mana SME Malaysia betul-betul beroperasi.',
 NULL, NULL, NULL),
(gen_random_uuid(), '4bd85981-867a-4fe8-a296-5131d887f038', 3,
 'Invite your first staff member from Settings so they log in with their own account instead of sharing yours.',
 'Jemput staf pertama anda dari Tetapan supaya mereka log masuk dengan akaun sendiri bukan berkongsi akaun anda.',
 'Every staff member having their own login is what makes the Audit Log (who did what, when) actually meaningful, and matters if you ever need to prove who approved a transaction.',
 'Setiap staf ada login sendiri adalah apa yang buat Log Audit (siapa buat apa, bila) betul-betul bermakna, dan penting kalau anda perlu buktikan siapa luluskan sesuatu transaksi.',
 'settings'),

-- dashboard
(gen_random_uuid(), 'fe61436e-7902-45c7-b50e-6fecb9d42043', 1,
 'The KPI cards at the top show your most time-sensitive numbers first — sales, overdue invoices, low stock — so you react before they become a bigger problem.',
 'Kad KPI di atas tunjuk nombor paling sensitif-masa dulu — jualan, invois tertunggak, stok rendah — supaya anda bertindak sebelum ia jadi masalah lebih besar.',
 '"Recognised Sales" on the Sales Trend card adds up Paid AND Partial invoices plus POS sales — not Unpaid ones. It is money you have actually collected or at least partly received, not just money you have invoiced out.',
 '"Jualan Diiktiraf" pada kad Trend Jualan jumlahkan invois Paid DAN Partial serta jualan POS — bukan yang Unpaid. Ia duit yang betul-betul dikutip atau sekurang-kurangnya sebahagian diterima, bukan sekadar duit yang diinvoiskan keluar.',
 NULL),
(gen_random_uuid(), 'fe61436e-7902-45c7-b50e-6fecb9d42043', 2,
 'Zone Power is a bar-plus-line chart scoring several areas of your business (sales, collection, payroll, expenses, stock) from 0-100 against your own overall average.',
 'Zone Power adalah carta bar-plus-line yang skor beberapa bahagian bisnes anda (jualan, kutipan, gaji, perbelanjaan, stok) dari 0-100 berbanding purata keseluruhan anda sendiri.',
 NULL, NULL, NULL),
(gen_random_uuid(), 'fe61436e-7902-45c7-b50e-6fecb9d42043', 3,
 'Business Health is a radar chart plotting several axes (sales, collection, overdue, payroll, stock, expenses) at once.',
 'Kesihatan Bisnes adalah carta radar yang plot beberapa paksi (jualan, kutipan, tertunggak, gaji, stok, perbelanjaan) serentak.',
 'A radar chart makes it obvious which ONE axis is dragging the whole shape down — a lopsided radar is a faster diagnosis than scrolling through six separate numbers.',
 'Carta radar buat jelas paksi MANA satu yang menarik bentuk keseluruhan turun — radar tak seimbang adalah diagnosis lebih pantas dari scroll enam nombor berasingan.',
 NULL),
(gen_random_uuid(), 'fe61436e-7902-45c7-b50e-6fecb9d42043', 4,
 'The AI insight line under each card is a short, plain-language read of what changed and why — written fresh, not a fixed caption.',
 'Baris insight AI di bawah setiap kad adalah bacaan ringkas bahasa mudah tentang apa yang berubah dan kenapa — ditulis segar, bukan kapsyen tetap.',
 NULL, NULL, NULL),
(gen_random_uuid(), 'fe61436e-7902-45c7-b50e-6fecb9d42043', 5,
 'Card Shortcuts near the top let you jump straight to any specific card further down the Dashboard without scrolling.',
 'Pintasan Kad berhampiran atas bagi anda terus ke mana-mana kad tertentu lebih bawah Papan Pemuka tanpa scroll.',
 NULL, NULL, NULL),

-- crm
(gen_random_uuid(), 'adb1d67f-0da9-422e-95bf-8be61acd03d6', 1,
 'Click Add Customer and fill in name, phone, email and city — this is what lets that customer be picked instantly on any Quotation, Invoice or POS sale later.',
 'Klik Tambah Pelanggan dan isi nama, telefon, emel dan bandar — ini yang bolehkan pelanggan itu dipilih serta-merta pada mana-mana Sebut Harga, Invois atau jualan POS nanti.',
 NULL, NULL, NULL),
(gen_random_uuid(), 'adb1d67f-0da9-422e-95bf-8be61acd03d6', 2,
 'Customers and Suppliers are two different lists in this system.',
 'Pelanggan dan Pembekal adalah dua senarai berbeza dalam sistem ini.',
 'Add companies you SELL to here, under CRM. Companies you BUY from go under Purchasing → Suppliers instead — putting a supplier in the wrong list means it will not show up where you need it.',
 'Tambah syarikat yang anda JUAL kepada di sini, di bawah CRM. Syarikat yang anda BELI dari pula di bawah Perolehan → Pembekal — letak pembekal dalam senarai salah bermakna ia tak akan muncul di tempat yang diperlukan.',
 'crm'),
(gen_random_uuid(), 'adb1d67f-0da9-422e-95bf-8be61acd03d6', 3,
 'Open a customer''s detail page and use Statement of Account (SOA) to see every invoice and payment for that one customer at a glance — handy right before an aging chase-up call.',
 'Buka halaman detail pelanggan dan guna Penyata Akaun (SOA) untuk lihat setiap invois dan bayaran untuk pelanggan itu sekali imbas — berguna sebelum panggilan kejar tunggakan.',
 NULL, NULL, NULL),
(gen_random_uuid(), 'adb1d67f-0da9-422e-95bf-8be61acd03d6', 4,
 'Deleting a customer is a soft delete, not a hard delete.',
 'Padam pelanggan adalah padam lembut, bukan padam keras.',
 'The record is only hidden (a deleted_at timestamp is set), not actually erased — every historical invoice for that customer stays intact and correct in your reports.',
 'Rekod itu cuma disorok (cap masa deleted_at ditetapkan), bukan betul-betul dipadam — setiap invois sejarah untuk pelanggan itu kekal utuh dan betul dalam laporan anda.',
 NULL),

-- sales L1 quotation
(gen_random_uuid(), '4a61893a-3454-4d82-96f7-50b41a09617b', 1,
 'From Sales, switch to the Quotations tab and click Add Quotation — pick the customer first, then add line items.',
 'Dari Jualan, tukar ke tab Sebut Harga dan klik Tambah Sebut Harga — pilih pelanggan dulu, kemudian tambah item baris.',
 NULL, NULL, 'sales'),
(gen_random_uuid(), '4a61893a-3454-4d82-96f7-50b41a09617b', 2,
 'Pick an item from your product catalog or type a custom line if it is not in Inventory.',
 'Pilih item dari katalog produk anda atau taip baris tersendiri kalau ia tiada dalam Inventori.',
 'Picking a real product auto-fills its price from Inventory''s unit price, but you can still override it for a one-off discount — the override only affects this Quotation, not the product''s master price.',
 'Pilih produk sebenar auto-isi harga dari harga unit Inventori, tapi anda masih boleh override untuk diskaun sekali sahaja — override itu hanya beri kesan kepada Sebut Harga ini, bukan harga induk produk.',
 NULL),
(gen_random_uuid(), '4a61893a-3454-4d82-96f7-50b41a09617b', 3,
 'Save it — a Quotation has no effect on your revenue or receivables until it is converted, so feel free to revise it as many times as the negotiation needs.',
 'Simpan — Sebut Harga tiada kesan ke atas hasil atau piutang anda sehingga ia ditukar, jadi bebas semak semula sebanyak mana rundingan perlukan.',
 NULL, NULL, NULL),

-- sales L2 convert
(gen_random_uuid(), 'cc8d3411-f3b9-43af-b84f-544e13d52790', 1,
 'Once the customer agrees to the price, open that Quotation and click Convert to Invoice.',
 'Sebaik pelanggan bersetuju dengan harga, buka Sebut Harga itu dan klik Tukar kepada Invois.',
 'A Quotation only becomes a real, collectible receivable once converted — it never appears in your revenue or overdue reports before that, no matter how long it sits as a draft.',
 'Sebut Harga hanya jadi piutang sebenar yang boleh dikutip sebaik ditukar — ia tak pernah muncul dalam laporan hasil atau tertunggak anda sebelum itu, walau berapa lama ia jadi draf.',
 NULL),
(gen_random_uuid(), 'cc8d3411-f3b9-43af-b84f-544e13d52790', 2,
 'The Quotation''s own status flips to Converted, and a brand-new Invoice is created with its own reference number.',
 'Status Sebut Harga itu sendiri bertukar jadi Converted, dan Invois baru dicipta dengan nombor rujukan sendiri.',
 NULL, NULL, NULL),
(gen_random_uuid(), 'cc8d3411-f3b9-43af-b84f-544e13d52790', 3,
 'You can still adjust the Invoice''s items right after conversion if something changed at the last minute — but once a payment is recorded against it, treat the Invoice as final.',
 'Anda masih boleh laras item Invois sebaik selepas pertukaran kalau ada perubahan saat akhir — tapi sebaik bayaran direkod ke atasnya, anggap Invois itu muktamad.',
 NULL, NULL, NULL),

-- sales L3 record payment
(gen_random_uuid(), 'acfb18e1-a700-4f5e-9c7e-914695657b5e', 1,
 'Open the Invoice and click Record Payment, then enter the amount, date and method received.',
 'Buka Invois dan klik Rekod Bayaran, kemudian isi jumlah, tarikh dan kaedah bayaran diterima.',
 'Enter less than the full outstanding amount and the invoice status automatically flips to "Partial" instead of "Paid" — you never have to set the status yourself.',
 'Masukkan kurang dari jumlah tertunggak penuh dan status invois secara automatik bertukar ke "Partial" bukan "Paid" — anda tak perlu tetapkan status sendiri.',
 NULL),
(gen_random_uuid(), 'acfb18e1-a700-4f5e-9c7e-914695657b5e', 2,
 'Watch the status: Paid means fully settled, Partial means some money is in but a balance remains, Unpaid means nothing has come in yet.',
 'Perhati status: Paid bermakna diselesaikan penuh, Partial bermakna sebahagian duit dah masuk tapi baki masih ada, Unpaid bermakna tiada apa masuk lagi.',
 'Dashboard "Recognised Sales" and most collection KPIs count Paid AND Partial invoices as revenue you have actually received — only truly Unpaid invoices are excluded, since a customer who paid half has already given you real money.',
 '"Jualan Diiktiraf" Papan Pemuka dan kebanyakan KPI kutipan kira invois Paid DAN Partial sebagai hasil yang betul-betul diterima — hanya invois Unpaid sebenar dikecualikan, sebab pelanggan yang bayar separuh dah beri anda duit sebenar.',
 NULL),
(gen_random_uuid(), 'acfb18e1-a700-4f5e-9c7e-914695657b5e', 3,
 'Record additional payments the same way any time more money comes in, until the balance reaches zero and the status becomes Paid on its own.',
 'Rekod bayaran tambahan cara sama bila-bila lagi duit masuk, sehingga baki jadi sifar dan status bertukar Paid dengan sendirinya.',
 NULL, NULL, NULL),

-- sales L4 overdue
(gen_random_uuid(), '2c5cbb0a-e25d-47fa-acba-be79cd4272d9', 1,
 'An invoice becomes Overdue by itself once its due date has passed while it is still Unpaid or Partial — you do not mark this manually.',
 'Invois jadi Tertunggak dengan sendirinya sebaik tarikh matangnya lepas sedangkan ia masih Unpaid atau Partial — anda tak tandakan ini secara manual.',
 'Overdue = (Unpaid OR Partial) AND past due date, excluding Cancelled invoices. A fully Paid invoice never counts as overdue again even if it was once paid late.',
 'Overdue = (Unpaid ATAU Partial) DAN lepas tarikh matang, mengecualikan invois Cancelled. Invois yang dah Paid penuh tak pernah dikira tertunggak lagi walaupun ia pernah dibayar lewat.',
 NULL),
(gen_random_uuid(), '2c5cbb0a-e25d-47fa-acba-be79cd4272d9', 2,
 'Overdue invoices surface automatically on the Dashboard and in Notifications — you do not need to hunt for them across every customer.',
 'Invois tertunggak muncul secara automatik pada Papan Pemuka dan Notifikasi — anda tak perlu cari satu-satu merentasi setiap pelanggan.',
 NULL, NULL, 'dashboard'),
(gen_random_uuid(), '2c5cbb0a-e25d-47fa-acba-be79cd4272d9', 3,
 'Use the AI "Draft Reminder" button on an overdue invoice to generate a polite follow-up message you can send straight to the customer.',
 'Guna butang AI "Draf Peringatan" pada invois tertunggak untuk jana mesej susulan sopan yang boleh terus dihantar kepada pelanggan.',
 NULL, NULL, NULL),

-- sales L5 credit note
(gen_random_uuid(), '6bb9b7ac-584b-4352-b697-bd014547e871', 1,
 'When a customer returns goods, you gave a discount after the fact, or an invoice was simply wrong, create a Credit Note against that Invoice instead of editing or deleting it.',
 'Bila pelanggan pulangkan barang, anda beri diskaun selepas fakta, atau invois memang salah, cipta Nota Kredit terhadap Invois itu bukan edit atau padamnya.',
 NULL, NULL, 'sales'),
(gen_random_uuid(), '6bb9b7ac-584b-4352-b697-bd014547e871', 2,
 'The Credit Note reduces the amount the customer owes without erasing the original Invoice — both documents stay visible for audit and for the customer''s own records.',
 'Nota Kredit kurangkan jumlah pelanggan tanggung tanpa memadam Invois asal — kedua-dua dokumen kekal kelihatan untuk audit dan rekod pelanggan sendiri.',
 NULL, NULL, NULL),

-- pos
(gen_random_uuid(), '7f887d1b-6d63-4b5f-80bf-9b2ade7bce93', 1,
 'At the POS terminal, staff log in with their security PIN, then confirm the opening cash float before clicking Start Shift.',
 'Di terminal POS, staf log masuk dengan PIN keselamatan, kemudian sahkan float tunai pembukaan sebelum klik Mula Shift.',
 'The suggested opening float is last shift''s closing cash — comparing what is actually in the drawer against this suggestion catches a cash discrepancy right at the start of the shift, not at the end when it is harder to trace.',
 'Float pembukaan dicadangkan ialah tunai penutupan shift terakhir — bandingkan apa yang betul-betul dalam laci lawan cadangan ini kesan percanggahan tunai betul-betul di awal shift, bukan di hujung bila lebih sukar dijejaki.',
 NULL),
(gen_random_uuid(), '7f887d1b-6d63-4b5f-80bf-9b2ade7bce93', 2,
 'Add products to the cart, adjust quantity, then checkout to complete the sale.',
 'Tambah produk ke troli, laras kuantiti, kemudian checkout untuk lengkapkan jualan.',
 'Completing a sale automatically creates a stock-out movement and reduces that product''s stock quantity — there is no separate manual Inventory step needed after a POS sale.',
 'Lengkapkan jualan secara automatik cipta pergerakan stok-keluar dan kurangkan kuantiti stok produk itu — tiada langkah Inventori manual berasingan diperlukan selepas jualan POS.',
 NULL),
(gen_random_uuid(), '7f887d1b-6d63-4b5f-80bf-9b2ade7bce93', 3,
 'At the end of the shift, click Close Shift and count the cash physically in the drawer against what the system expects.',
 'Di hujung shift, klik Tutup Shift dan kira tunai secara fizikal dalam laci berbanding apa sistem jangka.',
 NULL, NULL, 'pos'),

-- inventory
(gen_random_uuid(), 'f722fd53-cc85-476b-b30c-d3d1089b0ca1', 1,
 'Add a product with both English and Malay names, a unit price, and a Reorder Point.',
 'Tambah produk dengan nama English dan Melayu, harga unit, dan Takat Pesan Semula.',
 'Reorder Point defaults to 5 units if you leave it blank. Once stock quantity drops to or below this number, the product is flagged Low Stock on the Dashboard and in Notifications — set it based on how fast that specific item actually sells, not a guess.',
 'Takat Pesan Semula lalai kepada 5 unit kalau anda biarkan kosong. Sebaik kuantiti stok jatuh ke atau bawah nombor ini, produk itu ditanda Stok Rendah pada Papan Pemuka dan Notifikasi — tetapkan berdasarkan seberapa laju item khusus itu betul-betul terjual, bukan agak-agak.',
 'inventory'),
(gen_random_uuid(), 'f722fd53-cc85-476b-b30c-d3d1089b0ca1', 2,
 'Every change to a product''s stock quantity — a POS sale, a GRN receipt, a manual adjustment — is logged as a Stock Movement with a reason.',
 'Setiap perubahan pada kuantiti stok produk — jualan POS, penerimaan GRN, pelarasan manual — direkod sebagai Pergerakan Stok dengan sebab.',
 'This log is your audit trail if a stock count ever looks wrong — you can trace exactly which sale, receipt or adjustment moved the number, instead of guessing.',
 'Log ini adalah jejak audit anda kalau kiraan stok pernah nampak salah — anda boleh jejak tepat jualan, penerimaan atau pelarasan mana yang gerakkan nombor itu, bukan agak-agak.',
 NULL),
(gen_random_uuid(), 'f722fd53-cc85-476b-b30c-d3d1089b0ca1', 3,
 'Review the Low Stock list on the Dashboard periodically and raise a Purchase Order before you actually run out, not after.',
 'Semak senarai Stok Rendah pada Papan Pemuka secara berkala dan naikkan Pesanan Belian sebelum betul-betul kehabisan, bukan selepas.',
 NULL, NULL, 'purchasing'),

-- purchasing
(gen_random_uuid(), '6d5cd36a-3724-4d96-befe-159f045f523d', 1,
 'Create a Purchase Order listing the supplier and the items you intend to buy — this is a plan, and it does not change your stock yet.',
 'Cipta Pesanan Belian senaraikan pembekal dan item yang anda niat beli — ini adalah rancangan, dan ia belum tukar stok anda lagi.',
 NULL, NULL, 'purchasing'),
(gen_random_uuid(), '6d5cd36a-3724-4d96-befe-159f045f523d', 2,
 'When goods physically arrive, open that PO and use Receive Goods (GRN), entering the quantity actually received for each line.',
 'Bila barang betul-betul sampai, buka PO itu dan guna Terima Barang (GRN), masukkan kuantiti yang betul-betul diterima untuk setiap baris.',
 'You can receive LESS than what you ordered if the supplier ships in batches (a partial receive) — each GRN only adds stock for the quantity entered that time, and the PO stays open until every line is fully received.',
 'Anda boleh terima KURANG dari yang dipesan kalau pembekal hantar berbatch (terima separa) — setiap GRN hanya tambah stok untuk kuantiti dimasukkan kali itu, dan PO kekal terbuka sehingga setiap baris diterima penuh.',
 NULL),
(gen_random_uuid(), '6d5cd36a-3724-4d96-befe-159f045f523d', 3,
 'Once billed by the supplier, record a Supplier Bill referencing that PO/GRN, then record your payment against it when you actually pay.',
 'Sebaik dibil oleh pembekal, rekod Bil Pembekal merujuk PO/GRN itu, kemudian rekod bayaran anda apabila anda betul-betul bayar.',
 NULL, NULL, NULL),

-- production
(gen_random_uuid(), '6da56a89-9e04-45e2-9b39-69327bc9e81b', 1,
 'Pick the product you are making and the quantity to produce, and describe the materials needed as a free-text note for your team.',
 'Pilih produk yang anda buat dan kuantiti untuk dikeluarkan, dan terangkan bahan diperlukan sebagai nota teks bebas untuk pasukan anda.',
 'This module is intentionally simple — creating a Work Order does NOT automatically deduct raw materials from Inventory. "Materials Needed" is a note for your team, not a live stock reservation, so still adjust Inventory yourself if materials are actually consumed.',
 'Modul ini sengaja ringkas — cipta Work Order TIDAK menolak bahan mentah dari Inventori secara automatik. "Bahan Diperlukan" adalah nota untuk pasukan anda, bukan tempahan stok langsung, jadi tetap laras Inventori sendiri kalau bahan betul-betul digunakan.',
 'production'),
(gen_random_uuid(), '6da56a89-9e04-45e2-9b39-69327bc9e81b', 2,
 'Update the Work Order''s status by hand as production moves along, so whoever checks it later knows where things stand.',
 'Kemas kini status Work Order secara manual sambil pengeluaran berjalan, supaya sesiapa yang semak kemudian tahu keadaan sebenar.',
 NULL, NULL, NULL),

-- logistics
(gen_random_uuid(), '2d7e263e-cf00-480a-9f6e-d050165367e5', 1,
 'Create a Delivery Order linking an outgoing order to a driver name and vehicle number.',
 'Cipta Delivery Order kaitkan pesanan keluar dengan nama pemandu dan nombor kenderaan.',
 'Status here is updated manually by whoever is coordinating the delivery — there is no live GPS tracking behind it, so it is only as accurate and up to date as the last person who touched it.',
 'Status di sini dikemas kini secara manual oleh sesiapa yang menyelaras penghantaran — tiada penjejakan GPS langsung di belakangnya, jadi ia hanya setepat dan terkini seperti orang terakhir yang menyentuhnya.',
 'logistics'),
(gen_random_uuid(), '2d7e263e-cf00-480a-9f6e-d050165367e5', 2,
 'Keep the status updated as the delivery progresses so customers or your team calling in get an accurate answer.',
 'Kekalkan status dikemas kini sambil penghantaran berjalan supaya pelanggan atau pasukan anda yang bertanya dapat jawapan tepat.',
 NULL, NULL, NULL),

-- hr L1 employee/attendance
(gen_random_uuid(), 'dc922c5b-5915-4006-90a4-03117e50101d', 1,
 'Add an Employee with their IC number, position and basic salary — this is the record every payroll run and payslip later reads from.',
 'Tambah Pekerja dengan nombor IC, jawatan dan gaji pokok — ini rekod yang setiap larian gaji dan payslip nanti baca.',
 NULL, NULL, 'hr'),
(gen_random_uuid(), 'dc922c5b-5915-4006-90a4-03117e50101d', 2,
 'Staff clock in and out through the Attendance page — this is the record of who actually showed up, separate from Leave.',
 'Staf clock in dan out melalui halaman Kehadiran — ini rekod siapa yang betul-betul hadir, berasingan dari Cuti.',
 NULL, NULL, NULL),

-- hr L2 leave/outstation
(gen_random_uuid(), '95dc6ad7-6626-4084-b3bd-1af76063d039', 1,
 'An employee applies for Leave with a date range and reason; a manager then approves or rejects it before it is official.',
 'Pekerja mohon Cuti dengan julat tarikh dan sebab; pengurus kemudian luluskan atau tolak sebelum ia rasmi.',
 NULL, NULL, 'hr'),
(gen_random_uuid(), '95dc6ad7-6626-4084-b3bd-1af76063d039', 2,
 'Outstation is a separate request for field/off-site work (with location and purpose) that also needs approval, and shows up as a pending notification for whoever approves it.',
 'Outstation adalah permohonan berasingan untuk kerja lapangan/luar pejabat (dengan lokasi dan tujuan) yang juga perlukan kelulusan, dan muncul sebagai notifikasi tertunggak untuk sesiapa yang meluluskannya.',
 NULL, NULL, NULL),

-- hr L3 payroll/sd
(gen_random_uuid(), '3a3402f4-9515-49dc-8dde-a80a53518fcf', 1,
 'Click Run Payroll for a period — it calculates EPF, SOCSO, EIS and PCB for every employee at once based on their basic salary and age.',
 'Klik Jalankan Payroll untuk satu tempoh — ia kira EPF, SOCSO, EIS dan PCB untuk setiap pekerja serentak berdasarkan gaji pokok dan umur mereka.',
 'These calculations use the latest statutory rate structure known to the system (age/wage-tiered EPF, SOCSO/EIS with wage ceiling, progressive PCB brackets) — NOT the exact official RM-rounded wage-band tables, and PCB has no individual relief (spouse, child, insurance, etc). Always verify with KWSP/PERKESO/LHDN or a licensed accountant before official submission, especially for PCB.',
 'Kalkulasi ini guna struktur kadar berkanun terkini yang diketahui sistem (EPF ikut tier umur/gaji, SOCSO/EIS dengan siling gaji, PCB ikut jadual bertingkat) — BUKAN jadual RM-bulat rasmi tepat, dan PCB tiada relief individu (pasangan, anak, insurans, dll). Sentiasa sahkan dengan KWSP/PERKESO/LHDN atau akauntan bertauliah sebelum penyerahan rasmi, terutama untuk PCB.',
 NULL),
(gen_random_uuid(), '3a3402f4-9515-49dc-8dde-a80a53518fcf', 2,
 'Once payroll is generated, open Salary Disbursement to group everyone''s net pay into one bank-ready, printable batch.',
 'Sebaik gaji dijana, buka Penyaluran Gaji untuk kumpulkan gaji bersih semua orang jadi satu batch siap-bank, boleh cetak.',
 NULL, NULL, 'hr'),

-- hr L4 payslip
(gen_random_uuid(), 'f1eb4e45-20d3-4482-99fc-38dc6629a28a', 1,
 'A Payslip breaks earnings (basic salary, allowances, commission if any) apart from deductions (EPF, SOCSO, EIS, PCB) so the net pay figure at the bottom is traceable.',
 'Payslip pecahkan pendapatan (gaji pokok, elaun, komisyen jika ada) berasingan dari potongan (EPF, SOCSO, EIS, PCB) supaya angka gaji bersih di bawah boleh dijejak.',
 NULL, NULL, NULL),
(gen_random_uuid(), 'f1eb4e45-20d3-4482-99fc-38dc6629a28a', 2,
 'Staff (non-HR-admin roles) can view their own payslips under My Payslips — self only, they cannot see anyone else''s.',
 'Staf (peranan bukan-admin-HR) boleh lihat payslip sendiri di bawah Payslip Saya — diri sendiri sahaja, mereka tak boleh lihat orang lain.',
 NULL, NULL, NULL),

-- applicants
(gen_random_uuid(), '0dbe7d33-e07d-4f3b-850e-92f7b9675efa', 1,
 'Log an applicant with their details as they come in through your recruitment pipeline.',
 'Rekod pemohon dengan maklumat mereka sebaik masuk melalui saluran pengambilan anda.',
 NULL, NULL, 'applicants'),
(gen_random_uuid(), '0dbe7d33-e07d-4f3b-850e-92f7b9675efa', 2,
 'Once you decide to hire someone, open their applicant detail page and click Convert to Employee.',
 'Sebaik anda putuskan untuk ambil seseorang, buka halaman detail pemohon itu dan klik Tukar kepada Pekerja.',
 'This pre-fills the new Employee form with the applicant''s existing data and links back to the original application (converted_employee_id), so you never retype the same information twice and can always trace which hire came from which application.',
 'Ini pra-isi borang Pekerja baru dengan data pemohon sedia ada dan kaitkan semula ke permohonan asal (converted_employee_id), jadi anda tak pernah taip semula maklumat sama dua kali dan sentiasa boleh jejak pengambilan mana datang dari permohonan mana.',
 NULL),

-- accounting L1 coa
(gen_random_uuid(), '2c2f22e1-57cb-4d64-921c-fd5d242f59cd', 1,
 'The Chart of Accounts was seeded for you at onboarding from a template matching your industry, so you already start with sensible account names, not a blank list.',
 'Carta Akaun dah disemai untuk anda semasa onboarding dari templat sepadan industri anda, jadi anda dah mula dengan nama akaun munasabah, bukan senarai kosong.',
 NULL, NULL, 'accounting'),
(gen_random_uuid(), '2c2f22e1-57cb-4d64-921c-fd5d242f59cd', 2,
 'You can still add, rename or deactivate accounts as your business grows — every other module (invoices, payroll, expense claims) ultimately posts against one of these accounts.',
 'Anda masih boleh tambah, tukar nama atau nyahaktifkan akaun bila bisnes anda berkembang — setiap modul lain (invois, gaji, tuntutan) akhirnya siar terhadap salah satu akaun ini.',
 NULL, NULL, NULL),

-- accounting L2 journal
(gen_random_uuid(), 'fb8c85c0-a7af-4e63-ab0d-8ef27bda6b82', 1,
 'Most transactions already write their own journal entry automatically: paid invoices, POS sales, approved expense claims, paid supplier bills, generated payroll, and paid payment vouchers.',
 'Kebanyakan transaksi dah tulis entri jurnal sendiri secara automatik: invois dibayar, jualan POS, tuntutan perbelanjaan diluluskan, bil pembekal dibayar, gaji dijana, dan baucar bayaran dibayar.',
 NULL, NULL, NULL),
(gen_random_uuid(), 'fb8c85c0-a7af-4e63-ab0d-8ef27bda6b82', 2,
 'The manual Journal Entries screen is mainly for the smaller set of situations auto-posting does not cover, or for backfilling historical transactions that happened before this journal auto-posting existed.',
 'Skrin Entri Jurnal manual terutamanya untuk situasi lebih kecil yang auto-siar tak liputi, atau untuk mengisi kembali transaksi sejarah yang berlaku sebelum auto-siar jurnal ini wujud.',
 NULL, NULL, 'accounting'),

-- accounting L3 fiscal/period lock
(gen_random_uuid(), 'affa6c55-95ca-49db-865d-8f9d3c5ca7b6', 1,
 'Set your Fiscal Year so reports like the Income Statement know what "this year" actually means for your business.',
 'Tetapkan Tahun Kewangan supaya laporan seperti Penyata Pendapatan tahu apa maksud "tahun ini" untuk bisnes anda sebenarnya.',
 NULL, NULL, 'accounting'),
(gen_random_uuid(), 'affa6c55-95ca-49db-865d-8f9d3c5ca7b6', 2,
 'Once a month is fully reconciled and closed, set Period Lock (in Settings) through that date.',
 'Sebaik satu bulan diselaraskan penuh dan ditutup, tetapkan Kunci Tempoh (dalam Tetapan) sehingga tarikh itu.',
 'Invoices, payments and journals dated on or before the lock date are blocked at both the app and database level — lock a month only after you are truly done with it, since unlocking requires going back into Settings deliberately.',
 'Invois, bayaran dan jurnal bertarikh pada atau sebelum tarikh kunci disekat di peringkat aplikasi dan pangkalan data — kunci sebulan hanya selepas anda betul-betul selesai dengannya, sebab buka kunci perlukan kembali ke Tetapan dengan sengaja.',
 'settings'),
(gen_random_uuid(), 'affa6c55-95ca-49db-865d-8f9d3c5ca7b6', 3,
 'Record your Opening Balance (starting capital or bank balance) once, right at setup, so the Balance Sheet does not show a confusing negative cash position after your first payroll or bill payment.',
 'Rekod Baki Pembukaan (modal permulaan atau baki bank) sekali sahaja, waktu persediaan, supaya Kunci Kira-kira tak tunjuk kedudukan tunai negatif yang mengelirukan selepas gaji atau bayaran bil pertama anda.',
 NULL, NULL, NULL),

-- accounting L4 expense claims
(gen_random_uuid(), '0c660df7-7548-48e6-af06-a432a2a2d43f', 1,
 'A staff member submits an Expense Claim with a description, amount, and receipt for money they spent on the business.',
 'Staf hantar Tuntutan Perbelanjaan dengan keterangan, jumlah, dan resit untuk duit yang mereka belanja untuk bisnes.',
 NULL, NULL, 'accounting'),
(gen_random_uuid(), '0c660df7-7548-48e6-af06-a432a2a2d43f', 2,
 'Approving the claim is what triggers reimbursement and posts its own journal entry — an unapproved claim never touches your books.',
 'Meluluskan tuntutan itu yang mencetuskan bayaran balik dan siar entri jurnal sendiri — tuntutan yang tak diluluskan tak pernah sentuh buku anda.',
 NULL, NULL, NULL),

-- accounting L5 petty cash
(gen_random_uuid(), '3a3edc5f-c25b-4ac2-bcd3-9755e7a0f6c3', 1,
 'Petty Cash is a small imprest fund for tiny day-to-day expenses that do not deserve a full Payment Voucher — think parking, small office supplies.',
 'Petty Cash adalah dana imprest kecil untuk perbelanjaan harian kecil yang tak layak Baucar Bayaran penuh — fikir parkir, alat tulis pejabat kecil.',
 NULL, NULL, 'accounting'),
(gen_random_uuid(), '3a3edc5f-c25b-4ac2-bcd3-9755e7a0f6c3', 2,
 'Top up the fund and record what it was spent on regularly so the physical cash on hand always matches what the system expects.',
 'Isi semula dana dan rekod apa ia dibelanjakan secara kerap supaya tunai fizikal di tangan sentiasa padan dengan apa sistem jangka.',
 NULL, NULL, NULL),

-- accounting L6 bank recon
(gen_random_uuid(), 'a52f4c27-2e42-4e5c-924c-5d32b201aebd', 1,
 'Import or upload your bank statement, and the system will suggest matches between statement lines and transactions you have already recorded.',
 'Import atau muat naik penyata bank anda, dan sistem akan cadangkan padanan antara baris penyata dan transaksi yang anda dah rekod.',
 NULL, NULL, 'accounting'),
(gen_random_uuid(), 'a52f4c27-2e42-4e5c-924c-5d32b201aebd', 2,
 'Review every suggested match before confirming it.',
 'Semak setiap padanan dicadangkan sebelum sahkan.',
 'Matches are scored/suggested, not guaranteed correct — two different transactions can have the same amount on the same day, so a confident-looking suggestion still deserves a second look before you confirm it.',
 'Padanan dicadangkan/skor, bukan dijamin betul — dua transaksi berbeza boleh ada jumlah sama pada hari sama, jadi cadangan yang nampak yakin masih layak dilihat semula sebelum anda sahkan.',
 NULL),

-- vouchers
(gen_random_uuid(), '0ce7df18-11da-429c-99e6-846bd4321704', 1,
 'Create a Payment Voucher for money leaving the business outside the usual Supplier Bill flow — rent, utilities, or a one-off ad-hoc payment.',
 'Cipta Baucar Bayaran untuk duit keluar bisnes di luar aliran Bil Pembekal biasa — sewa, utiliti, atau bayaran ad-hoc sekali sahaja.',
 NULL, NULL, 'vouchers'),
(gen_random_uuid(), '0ce7df18-11da-429c-99e6-846bd4321704', 2,
 'A Payment Voucher posts straight to your ledger once confirmed — it is a formal accounting record, not a casual note.',
 'Baucar Bayaran terus disiar ke lejar anda sebaik disahkan — ia rekod perakaunan rasmi, bukan nota santai.',
 NULL, NULL, NULL),
(gen_random_uuid(), '0ce7df18-11da-429c-99e6-846bd4321704', 3,
 'Print it (or batch-print several) whenever you need a physical/PDF copy for signing or filing.',
 'Cetak (atau cetak-batch beberapa) bila-bila anda perlukan salinan fizikal/PDF untuk ditandatangan atau difailkan.',
 NULL, NULL, NULL),

-- reports
(gen_random_uuid(), '9639df7e-aaa6-4fd5-90a4-5784e684329f', 1,
 'The Income Statement (P&L) shows revenue minus expenses over a period — the single number at the bottom is your profit or loss for that period.',
 'Penyata Pendapatan (P&L) tunjuk hasil tolak perbelanjaan sepanjang satu tempoh — nombor tunggal di bawah adalah untung atau rugi anda untuk tempoh itu.',
 NULL, NULL, 'reports'),
(gen_random_uuid(), '9639df7e-aaa6-4fd5-90a4-5784e684329f', 2,
 'The Balance Sheet is a snapshot at one point in time (not a period) — what the business owns (assets), owes (liabilities), and what is left over for the owner (equity).',
 'Kunci Kira-kira adalah gambaran pada satu titik masa (bukan tempoh) — apa bisnes miliki (aset), tanggung (liabiliti), dan apa yang tinggal untuk pemilik (ekuiti).',
 'A profitable Income Statement and a healthy Balance Sheet are not the same thing — a business can be profitable on paper while still being cash-poor, which is exactly why both reports matter.',
 'Penyata Pendapatan yang untung dan Kunci Kira-kira yang sihat bukan perkara sama — bisnes boleh untung di atas kertas sedangkan masih kekurangan tunai, sebab itulah kedua-dua laporan penting.',
 NULL),
(gen_random_uuid(), '9639df7e-aaa6-4fd5-90a4-5784e684329f', 3,
 'The Sales Report breaks revenue down by customer, product or sales person for a period, so you can see who and what is actually driving the number on the Income Statement.',
 'Laporan Jualan pecahkan hasil ikut pelanggan, produk atau jurujual untuk satu tempoh, supaya anda nampak siapa dan apa yang betul-betul menjana nombor pada Penyata Pendapatan.',
 NULL, NULL, NULL),
(gen_random_uuid(), '9639df7e-aaa6-4fd5-90a4-5784e684329f', 4,
 'AR Aging and AP Aging (also under Reports) bucket your unpaid receivables and payables by how overdue they are — a fast way to see which balances need the most urgent attention.',
 'AR Aging dan AP Aging (juga di bawah Laporan) kumpulkan piutang dan hutang belum bayar anda ikut seberapa tertunggak — cara pantas nampak baki mana perlukan perhatian paling segera.',
 NULL, NULL, NULL);
